### ISSUE TITLE
Rococo Slot Request for Polkadex Testnet

### ISSUE THREAD

**Issue by zktony** [paritytech/subport#535]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Polkadex

### Parachain Name

kaizen

### ParaID

2040

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[para-2040-genesis-state.zip](https://github.com/paritytech/subport/files/10731877/para-2040-genesis-state.zip)

### Upload your Validation Code (genesis runtime Wasm)

[para-2040-wasm.zip](https://github.com/paritytech/subport/files/10731879/para-2040-wasm.zip)

### Anything else we should know?

We want to open a channel with Rockmint and Astar.

### Register your Rococo parachain details for `polkadot-js/apps`

https://github.com/polkadot-js/apps/pull/9022

**Comment by mcdonagg** [comment]
Hi @al3mart can you please advise on next steps?

**Comment by al3mart** [comment]
Registering your parathread atm, once finished will assign your paraId the slot.

**Comment by zktony** [comment]
Hey @al3mart, let us know if we have to do anything else from our side.

**Comment by al3mart** [comment]
Slot assigned, onboarding happening in 1h49' from now.

**Comment by zktony** [comment]
Hey @al3mart , I am getting following error:-
```
Feb 27 05:25:34 ip-10-211-27-118 parachain-polkadex-node[377287]: 2023-02-27 05:25:34.214  INFO main parachain_polkadex_node::command: Parachain id: Id(2040)
Feb 27 05:25:34 ip-10-211-27-118 parachain-polkadex-node[377287]: 2023-02-27 05:25:34.214  INFO main parachain_polkadex_node::command: Parachain Account: 5Ec4AhPcxFrEE36CYS2HJYaqx42mqmeEHsgHh3dWxHryeNKs
Feb 27 05:25:34 ip-10-211-27-118 parachain-polkadex-node[377287]: 2023-02-27 05:25:34.214  INFO main parachain_polkadex_node::command: Parachain genesis state: 0x000000000000000000000000000000000000000000000000000000000000000000797c4f91a722fff467c88f88de45ab9a6b2eb2058ad88597e21088e9108f788a03170a2e7597b7b7e3d84c>
Feb 27 05:25:34 ip-10-211-27-118 parachain-polkadex-node[377287]: 2023-02-27 05:25:34.214  INFO main parachain_polkadex_node::command: Is collating: yes
Feb 27 05:26:50 ip-10-211-27-118 parachain-polkadex-node[377287]: 2023-02-27 05:26:50.867  INFO tokio-runtime-worker substrate: [Parachain] 💤 Idle (0 peers), best: #0 (0xa419…7d70), finalized #0 (0xa419…7d70), ⬇ 79 B/s ⬆ 78 B/s
Feb 27 05:26:54 ip-10-211-27-118 parachain-polkadex-node[377287]: 2023-02-27 05:26:54.546  INFO tokio-runtime-worker substrate: [Relaychain] ✨ Imported #4286923 (0xf25a…0be3)
Feb 27 05:26:54 ip-10-211-27-118 parachain-polkadex-node[377287]: 2023-02-27 05:26:54.548 ERROR tokio-runtime-worker cumulus-collator: [Parachain] Could not find the header of the genesis block in the database! block_hash=0xa456557a83b5c02d76810742df70cddeb5cec0954e8372367425cedd78c54030
```
This [issue](https://github.com/paritytech/cumulus/issues/385) says it is related to genesis state. But I shared right file with this issue. Let me know, if I am missing something. Thanks

**Comment by al3mart** [comment]
I have set your state again, let me know what is the outcome now.

**Comment by zktony** [comment]
Hey @al3mart, I am still getting the same error. 😕

**Comment by zktony** [comment]
Let me redeploy everything again. I will send you new files in some time.

**Comment by zktony** [comment]
[share.zip](https://github.com/paritytech/subport/files/10868923/share.zip)
The following file contains chain_spec(plain text), para-2040-genesis-state and para-2040-wasm.

**Comment by al3mart** [comment]
Done! Set again.

**Comment by zktony** [comment]
Still getting the same error 😓
```
Mar 03 05:26:00 ip-10-211-27-118 parachain-polkadex-node[511698]: 2023-03-03 05:26:00.507  INFO tokio-runtime-worker substrate: [Relaychain] ✨ Imported #4344505 (0x6732…4d88)
Mar 03 05:26:00 ip-10-211-27-118 parachain-polkadex-node[511698]: 2023-03-03 05:26:00.510 ERROR tokio-runtime-worker cumulus-collator: [Parachain] Could not find the header of the genesis block in the database! block_hash=0xdfef2f2a513987ee5393a9f21f86843db36bc2e5d22e90ad22a1095ccf754ffb
Mar 03 05:26:01 ip-10-211-27-118 parachain-polkadex-node[511698]: 2023-03-03 05:26:01.213  INFO tokio-runtime-worker substrate: [Relaychain] 💤 Idle (32 peers), best: #4344505 (0x6732…4d88), finalized #4344502 (0x4a20…dc56), ⬇ 64.2kiB/s ⬆ 63.0kiB/s
Mar 03 05:26:01 ip-10-211-27-118 parachain-polkadex-node[511698]: 2023-03-03 05:26:01.240  INFO tokio-runtime-worker substrate: [Parachain] 💤 Idle (0 peers), best: #0 (0xa419…7d70), finalized #0 (0xa419…7d70), ⬇ 0 ⬆ 0 
```
Could you please cross check my spec file? If I configd it correctly or not?

**Comment by al3mart** [comment]
Firstly I would change
`"chainType": "Local",` to `"chainType": "Live",

Even though that error indicates a mismatch on the state :thinking:
